# Run the build docker image using file system resources
# Usage:
# $ docker compose build --no-cache --pull
# $ docker compose up --force-recreate --detach
# $ docker compose logs --tail="all" --follow
# $ docker compose down --remove-orphans
# Browse: curl --head http://localhost:8091/index.html
# Browse: curl --head http://localhost:8091/content/content.html
version: '3.8'
services:
  diy-accounting-mdcms:
    build:
      context: .
    ports:
      - 8091:80
